### ISSUE TITLE
fxlabs api support

### ISSUE THREAD

**Issue by abiank** [oanda/oandajs#5]
Hello, I expected this call to work:

OANDA.api("/labs/v1/historical_position_ratios","GET",{instrument:"EUR_USD",period:86400},function(x){console.log(x)})

..but it doesn't, throwing this in chrome on linux:

OPTIONS https://api-fxtrade.oanda.com/labs/v1/historical_position_ratios?instrument=EUR_USD&period=86400 401 (Unauthorized) 
XMLHttpRequest cannot load https://api-fxtrade.oanda.com/labs/v1/historical_position_ratios?instrument=EUR_USD&period=86400. Invalid HTTP status code 401 

Why does it call the OPTIONS method first? Is it a jquery thing? The equivalent curl command executes flawlessly.

**Comment by abendigo** [comment]
Browsers uses something called CORS when accessing URL's from domains different from the one that the page was served from. You can read a little more about it here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

When you use CURL from the command line, it does not have to worry about CORS, and so the OPTIONS request is never sent.

I am going to close this issue, as it has not been updated in 2 years. If you feel that there is still a problem, please open a new issue.
